### PR TITLE
updated day 42 activities

### PR DESCRIPTION
**Pull request by ambigai-rajan**

### CODE REVIEW

**Comment by ambigai-rajan** [comment]
[Updating Day-42 work[Ambigai Rajan]](https://trello.com/c/6jL5MZcM/18-updating-day-42-workambigai-rajan)

**Review by sathyanmadhavan — CHANGES_REQUESTED** [review]
Post your pythonanywhere link and blog found useful for software testing

**Review by shivahari — CHANGES_REQUESTED** [review]
Can you post the blogs you are referring for `Software testing`

**Comment by ambigai-rajan** [comment]
> Post your pythonanywhere link and blog found useful for software testing

added link to Pythonanywhere ,references for Software testing and I just started learning

**Comment by ambigai-rajan** [comment]
> Can you post the blogs you are referring for `Software testing`

added links I used to learn software testing

**Review by shivahari — APPROVED** [review]

**Review by sathyanmadhavan — APPROVED** [review]

**Pull request merged**
